[package]
name = "jedinft"
version = "1.0.0"
description = "NFT Contract For LP Contest"
# homepage = "https://github.com/auditless/cairo-template"

[scripts]

[dependencies]
starknet = ">=2.0.0"
alexandria = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
rules_erc721 = { git = "https://github.com/FelixGibson/starknet-erc721-rules.git", branch = "p/felix" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "experimental"