[package]
name = "jedinft"
version = "1.0.0"
description = "NFT Contract For LP Contest"
# homepage = "https://github.com/auditless/cairo-template"

[scripts]

[workspace]
members = ["alexandria_data_structures"]

[workspace.dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }


[dependencies]
starknet = ">=2.2.0"
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
# rules_erc721 = { git = "https://github.com/ruleslabs/starknet-erc721.git" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.7.0" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs-list.name = "experimental"